# Generated by Django 3.0.3 on 2020-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200319_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='slug',
            field=models.SlugField(blank=0, default='abc'),
        ),
    ]
