# Generated by Django 3.0.3 on 2020-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_producttable_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='slug',
            field=models.SlugField(blank=0, default='abc', unique=True),
        ),
    ]
