# Generated by Django 3.0.3 on 2020-03-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200319_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
        migrations.DeleteModel(
            name='ProductQuerySet',
        ),
    ]
