# Generated by Django 3.0.3 on 2020-03-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200330_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingprofile',
            new_name='billing_profile',
        ),
    ]
