# Generated by Django 3.0.3 on 2020-03-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_logintable_registertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registertable',
            name='cpass',
        ),
    ]
