# Generated by Django 3.0.3 on 2020-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product/'),
        ),
    ]
