# Generated by Django 3.0.3 on 2020-03-25 18:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
