# Generated by Django 3.0.3 on 2020-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameL', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameR', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('dob', models.DateField(default=None)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=120)),
                ('cpass', models.CharField(max_length=120)),
            ],
        ),
    ]
